use std::path::Path;
use std::process::Command;

use sha2::{Digest, Sha256};

use crate::compare::Surface;
use crate::packages::{Kind, Package};

/// Files whose content the Rust and TypeScript API extractions already cover.
pub fn is_source(path: &str, kind: Kind) -> bool {
    match kind {
        Kind::Cargo => path.ends_with(".rs"),
        Kind::Npm => [".ts", ".js", ".mjs", ".cjs", ".map"]
            .iter()
            .any(|ext| path.ends_with(ext)),
    }
}

/// One item per JSON scalar and per empty array or object, keyed by its JSON
/// pointer (RFC 6901), so a difference names the exact place in the file.
pub fn flatten_json(prefix: &str, value: &serde_json::Value, s: &mut Surface) {
    fn walk(prefix: &str, pointer: String, value: &serde_json::Value, s: &mut Surface) {
        match value {
            serde_json::Value::Object(map) if !map.is_empty() => {
                for (k, v) in map {
                    let token = k.replace('~', "~0").replace('/', "~1");
                    walk(prefix, format!("{pointer}/{token}"), v, s);
                }
            }
            serde_json::Value::Array(items) if !items.is_empty() => {
                for (i, v) in items.iter().enumerate() {
                    walk(prefix, format!("{pointer}/{i}"), v, s);
                }
            }
            other => s.insert(format!("{prefix}#{pointer}"), other.to_string()),
        }
    }
    walk(prefix, String::new(), value, s);
}

/// A listed file that is not in the source tree is written by the packaging
/// command itself (for Cargo: `.cargo_vcs_info.json`, `Cargo.toml.orig`).
fn file_items(dir: &Path, path: &str, packager: &str, s: &mut Surface) -> Result<(), String> {
    let full = dir.join(path);
    if !full.exists() {
        s.insert(format!("file {path}"), format!("generated by {packager}"));
        return Ok(());
    }
    let bytes = std::fs::read(&full).map_err(|e| format!("reading {}: {e}", full.display()))?;
    if path.ends_with(".json") {
        let value: serde_json::Value = serde_json::from_slice(&bytes)
            .map_err(|e| format!("parsing {}: {e}", full.display()))?;
        flatten_json(&format!("file {path}"), &value, s);
    } else {
        s.insert(
            format!("file {path}"),
            format!("sha256 {}", hex::encode(Sha256::digest(&bytes))),
        );
    }
    Ok(())
}

/// The non-source files `cargo package --list` ships.
pub fn cargo_files(pkg: &Package) -> Result<Surface, String> {
    let out = Command::new("cargo")
        .args(["package", "--list", "--allow-dirty", "--manifest-path"])
        .arg(&pkg.manifest)
        .output()
        .map_err(|e| format!("running cargo package: {e}"))?;
    if !out.status.success() {
        return Err(String::from_utf8_lossy(&out.stderr).into_owned());
    }
    let mut s = Surface::default();
    for path in String::from_utf8_lossy(&out.stdout)
        .lines()
        .filter(|p| !is_source(p, Kind::Cargo))
    {
        file_items(&pkg.dir, path, "cargo package", &mut s)?;
    }
    Ok(s)
}

/// The non-source files of an npm package, given the paths
/// `npm publish --dry-run` listed.
pub fn npm_files(pkg: &Package, listed: &[String]) -> Result<Surface, String> {
    let mut s = Surface::default();
    for path in listed.iter().filter(|p| !is_source(p, Kind::Npm)) {
        file_items(&pkg.dir, path, "npm publish", &mut s)?;
    }
    Ok(s)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compare::compare;

    #[test]
    fn json_flattens_to_one_key_per_scalar_and_empty_container() {
        let mut s = Surface::default();
        flatten_json(
            "file d.json",
            &serde_json::json!({"staging": [{"chainId": 1}], "production": [], "a/b": {"~": true}}),
            &mut s,
        );
        let lines = compare("p", &s, &Surface::default());
        let got: Vec<(&str, &str)> = lines
            .iter()
            .map(|l| (l.key.as_str(), l.evm[0].as_str()))
            .collect();
        assert_eq!(
            got,
            vec![
                ("file d.json#/a~1b/~0", "true"),
                ("file d.json#/production", "[]"),
                ("file d.json#/staging/0/chainId", "1"),
            ]
        );
    }

    #[test]
    fn sources_are_left_to_the_api_extractions() {
        assert!(is_source("src/lib.rs", Kind::Cargo));
        assert!(!is_source("deployments.json", Kind::Cargo));
        for p in [
            "dist/index.d.ts",
            "dist/index.js",
            "src/a.ts",
            "dist/a.js.map",
            "x.mjs",
            "x.cjs",
        ] {
            assert!(is_source(p, Kind::Npm), "{p}");
        }
        assert!(!is_source("package.json", Kind::Npm));
    }
}
