//! The on-chain interface of a program, read from the record its client
//! package binds: an EVM contract's JSON ABI (a `.json` file, or the one
//! `forge bind` embeds in the bindings it generates) and a Solana program's
//! Anchor IDL. Both read into one vocabulary, so a paired contract and program
//! compare entry by entry:
//!
//! - `fn <name>`: a function or instruction, with its arguments and return.
//!   A Solana instruction's account list has no EVM counterpart and is left
//!   out.
//! - `event <name>`: an event with its fields. An EVM field's `indexed` flag
//!   (a log topic) has no Solana counterpart and is left out.
//! - `error <name>`: a custom error. An Anchor error carries a code and a
//!   message but no fields, so only its name compares.
//! - `type <name>`: a struct or enum the entries above use, with its fields.
//! - `account <name>`: a Solana account's layout, which has no EVM
//!   counterpart (an EVM contract's storage is reached through its
//!   functions).
//!
//! Names follow each language's convention, so they compare in snake_case
//! (functions, arguments, fields) or as written (types, events, errors), an
//! event's name without the `Event` suffix the Solana programs give theirs.
//! Types compare in one notation: `u<N>` / `i<N>`, `bool`, `string`, `bytes`,
//! `bytes<N>` (a fixed byte array: Solidity `bytes32`, Anchor `[u8; 32]`),
//! `vec<T>`, `[T; N]`, `option<T>`, a defined type by name, and `address` for
//! an account's identifier (Solidity `address`, Anchor `pubkey`).

use std::path::Path;

use anyhow::{Context, bail};
use serde_json::Value;

use crate::compare::Surface;

/// The marker `forge bind` writes before the JSON ABI it embeds in a
/// generated module's documentation.
const FORGE_BIND_ABI: &str = "...which was generated by the following JSON ABI:\n```json\n";

/// The interface of the EVM contract whose ABI `path` holds: a `.json` ABI,
/// or a `forge bind` module embedding one.
pub fn abi_file(path: &Path) -> anyhow::Result<Surface> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let json = if path.extension().is_some_and(|e| e == "json") {
        text.as_str()
    } else {
        let (_, after) = text
            .split_once(FORGE_BIND_ABI)
            .with_context(|| format!("{} embeds no forge bind JSON ABI", path.display()))?;
        let (json, _) = after
            .split_once("\n```")
            .with_context(|| format!("the JSON ABI in {} is not closed", path.display()))?;
        json
    };
    let abi: Value = serde_json::from_str(json)
        .with_context(|| format!("parsing the ABI in {}", path.display()))?;
    abi_surface(&abi)
}

/// The interface of the Solana program whose Anchor IDL `path` holds.
pub fn idl_file(path: &Path) -> anyhow::Result<Surface> {
    let text =
        std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let idl: Value = serde_json::from_str(&text)
        .with_context(|| format!("parsing the IDL {}", path.display()))?;
    idl_surface(&idl)
}

fn abi_surface(abi: &Value) -> anyhow::Result<Surface> {
    let mut s = Surface::default();
    for entry in abi.as_array().context("an ABI is a JSON array")? {
        let kind = str_field(entry, "type")?;
        match kind {
            "function" => {
                let name = str_field(entry, "name")?;
                let args = abi_params(entry, "inputs", &mut s)?;
                let returns = abi_params(entry, "outputs", &mut s)?
                    .into_iter()
                    .map(|(_, ty)| ty)
                    .collect::<Vec<_>>();
                s.insert(
                    format!("fn {}", snake_case(name)),
                    signature(&args, &returns),
                );
            }
            "event" => {
                let fields = abi_params(entry, "inputs", &mut s)?;
                s.insert(
                    format!("event {}", event_name(str_field(entry, "name")?)),
                    fields_value(&fields),
                );
            }
            "error" => {
                s.insert(format!("error {}", str_field(entry, "name")?), "error");
            }
            // How a contract is created or receives plain ether: no entry a
            // Solana program has.
            "constructor" | "receive" | "fallback" => {}
            other => bail!("an ABI entry of type {other}"),
        }
    }
    Ok(s)
}

/// The named parameters of an ABI entry, each struct among their types also
/// recorded as a `type`.
fn abi_params(
    entry: &Value,
    field: &str,
    s: &mut Surface,
) -> anyhow::Result<Vec<(String, String)>> {
    let Some(params) = entry.get(field) else {
        return Ok(vec![]);
    };
    params
        .as_array()
        .with_context(|| format!("an ABI entry's {field} is a JSON array"))?
        .iter()
        .map(|p| Ok((snake_case(str_field(p, "name")?), abi_type(p, s)?)))
        .collect()
}

/// An ABI parameter's type in the common notation.
fn abi_type(param: &Value, s: &mut Surface) -> anyhow::Result<String> {
    let ty = str_field(param, "type")?;
    let internal = param
        .get("internalType")
        .and_then(Value::as_str)
        .unwrap_or("");
    if let Some(element) = ty.strip_suffix("[]") {
        let inner = element_param(param, element, internal.strip_suffix("[]"));
        return Ok(format!("vec<{}>", abi_type(&inner, s)?));
    }
    if let Some((element, len)) = ty.strip_suffix(']').and_then(|t| t.rsplit_once('[')) {
        let inner_internal = internal.rsplit_once('[').map(|(i, _)| i);
        let inner = element_param(param, element, inner_internal);
        return Ok(format!("[{}; {len}]", abi_type(&inner, s)?));
    }
    if ty == "tuple" {
        let name = internal
            .strip_prefix("struct ")
            .map(|n| n.rsplit('.').next().unwrap_or(n))
            .context("a tuple parameter's internalType names its struct")?
            .to_owned();
        let fields = abi_params(param, "components", s)?;
        s.insert(format!("type {name}"), fields_value(&fields));
        return Ok(name);
    }
    if let Some(name) = internal.strip_prefix("enum ") {
        return Ok(name.rsplit('.').next().unwrap_or(name).to_owned());
    }
    Ok(match ty {
        "address" | "bool" | "string" | "bytes" => ty.to_owned(),
        _ if ty.starts_with("uint") => format!("u{}", &ty[4..]),
        _ if ty.starts_with("int") => format!("i{}", &ty[3..]),
        _ if ty.starts_with("bytes") => ty.to_owned(),
        other => bail!("an ABI type {other}"),
    })
}

/// The element of an array parameter, as a parameter of its own.
fn element_param(param: &Value, element: &str, internal: Option<&str>) -> Value {
    let mut inner = param.clone();
    inner["type"] = element.into();
    if let Some(internal) = internal {
        inner["internalType"] = internal.into();
    }
    inner
}

fn idl_surface(idl: &Value) -> anyhow::Result<Surface> {
    let mut s = Surface::default();
    let events: Vec<&str> = idl_names(idl, "events")?;
    let accounts: Vec<&str> = idl_names(idl, "accounts")?;
    for instruction in array_field(idl, "instructions")? {
        let args = idl_fields(instruction, "args")?;
        let returns = match instruction.get("returns") {
            None | Some(Value::Null) => vec![],
            Some(ty) => vec![idl_type(ty)?],
        };
        s.insert(
            format!("fn {}", str_field(instruction, "name")?),
            signature(&args, &returns),
        );
    }
    for error in optional_array(idl, "errors")? {
        s.insert(format!("error {}", str_field(error, "name")?), "error");
    }
    for ty in optional_array(idl, "types")? {
        let name = str_field(ty, "name")?;
        let body = ty.get("type").context("an IDL type has a body")?;
        let value = match str_field(body, "kind")? {
            "struct" => fields_value(&idl_fields(body, "fields")?),
            "enum" => format!(
                "enum {{{}}}",
                array_field(body, "variants")?
                    .iter()
                    .map(|v| str_field(v, "name"))
                    .collect::<anyhow::Result<Vec<_>>>()?
                    .join(", ")
            ),
            other => bail!("an IDL type of kind {other}"),
        };
        let key = if events.contains(&name) {
            format!("event {}", event_name(name))
        } else if accounts.contains(&name) {
            format!("account {name}")
        } else {
            format!("type {name}")
        };
        s.insert(key, value);
    }
    Ok(s)
}

fn idl_names<'a>(idl: &'a Value, field: &str) -> anyhow::Result<Vec<&'a str>> {
    optional_array(idl, field)?
        .iter()
        .map(|entry| str_field(entry, "name"))
        .collect()
}

fn idl_fields(entry: &Value, field: &str) -> anyhow::Result<Vec<(String, String)>> {
    match entry.get(field) {
        None => Ok(vec![]),
        Some(fields) => array(fields)?
            .iter()
            .map(|f| Ok((str_field(f, "name")?.to_owned(), idl_type(&f["type"])?)))
            .collect(),
    }
}

/// An IDL type in the common notation.
fn idl_type(ty: &Value) -> anyhow::Result<String> {
    if let Some(name) = ty.as_str() {
        return Ok(match name {
            "pubkey" => "address".to_owned(),
            other => other.to_owned(),
        });
    }
    if let Some(inner) = ty.get("vec") {
        return Ok(format!("vec<{}>", idl_type(inner)?));
    }
    if let Some(inner) = ty.get("option") {
        return Ok(format!("option<{}>", idl_type(inner)?));
    }
    if let Some(array) = ty.get("array") {
        let [element, len] = array.as_array().map(Vec::as_slice).unwrap_or_default() else {
            bail!("an IDL array type is [element, length], not {array}");
        };
        let len = len.as_u64().context("an IDL array length is a number")?;
        return Ok(if element == "u8" {
            format!("bytes{len}")
        } else {
            format!("[{}; {len}]", idl_type(element)?)
        });
    }
    if let Some(defined) = ty.get("defined") {
        let name = defined.get("name").unwrap_or(defined);
        return Ok(name
            .as_str()
            .context("an IDL defined type is named")?
            .to_owned());
    }
    bail!("an IDL type {ty}")
}

fn signature(args: &[(String, String)], returns: &[String]) -> String {
    let args = fields_value(args);
    match returns {
        [] => args,
        [one] => format!("{args} -> {one}"),
        many => format!("{args} -> ({})", many.join(", ")),
    }
}

fn fields_value(fields: &[(String, String)]) -> String {
    let fields: Vec<String> = fields.iter().map(|(n, t)| format!("{n}: {t}")).collect();
    format!("({})", fields.join(", "))
}

/// An event's name without the `Event` suffix the Solana programs give it.
fn event_name(name: &str) -> &str {
    name.strip_suffix("Event").unwrap_or(name)
}

/// `name` in snake_case: an underscore before each capital that starts a new
/// word (after a lowercase letter or digit, or a capital followed by a
/// lowercase letter, which ends an acronym), all lowercase.
pub(crate) fn snake_case(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut out = String::with_capacity(name.len() + 4);
    for (i, &c) in chars.iter().enumerate() {
        if c.is_ascii_uppercase() && i > 0 {
            let prev = chars[i - 1];
            let next_lower = chars.get(i + 1).is_some_and(char::is_ascii_lowercase);
            let starts_word = prev.is_ascii_lowercase()
                || prev.is_ascii_digit()
                || (prev.is_ascii_uppercase() && next_lower);
            if starts_word {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}

fn str_field<'a>(entry: &'a Value, field: &str) -> anyhow::Result<&'a str> {
    entry
        .get(field)
        .and_then(Value::as_str)
        .with_context(|| format!("an entry has no string {field}: {entry}"))
}

fn array(value: &Value) -> anyhow::Result<&Vec<Value>> {
    value
        .as_array()
        .with_context(|| format!("not a JSON array: {value}"))
}

/// The entries of the array `field` of `entry`, none when it is absent.
fn optional_array<'a>(entry: &'a Value, field: &str) -> anyhow::Result<&'a [Value]> {
    match entry.get(field) {
        None => Ok(&[]),
        Some(value) => Ok(array(value)?),
    }
}

fn array_field<'a>(entry: &'a Value, field: &str) -> anyhow::Result<&'a Vec<Value>> {
    array(
        entry
            .get(field)
            .with_context(|| format!("an entry has no {field}: {entry}"))?,
    )
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;
    use crate::compare::{Outcome, compare};

    #[test]
    fn names_compare_in_snake_case() {
        for (name, snake) in [
            ("setKindTableCommitment", "set_kind_table_commitment"),
            ("RISC_ZERO_VERIFIER_ROUTER", "risc_zero_verifier_router"),
            ("upgradeToAndCall", "upgrade_to_and_call"),
            ("isERC1967Proxy", "is_erc1967_proxy"),
            ("set_kind_table_commitment", "set_kind_table_commitment"),
        ] {
            assert_eq!(snake_case(name), snake, "{name}");
        }
    }

    /// The same function, event, error and struct, written once as Solidity
    /// emits them and once as Anchor does, compare equal; an instruction's
    /// accounts and an event field's `indexed` do not count.
    #[test]
    fn an_abi_and_an_idl_of_one_interface_match() {
        let abi = json!([
            {"type": "function", "name": "denyLogicRef", "stateMutability": "nonpayable",
             "inputs": [{"name": "logicRef", "type": "bytes32", "internalType": "bytes32"}],
             "outputs": []},
            {"type": "function", "name": "paused", "stateMutability": "view",
             "inputs": [], "outputs": [{"name": "isPaused", "type": "bool", "internalType": "bool"}]},
            {"type": "function", "name": "submit", "stateMutability": "nonpayable",
             "inputs": [{"name": "action", "type": "tuple", "internalType": "struct IPA.Action",
                         "components": [
                             {"name": "owner", "type": "address", "internalType": "address"},
                             {"name": "tags", "type": "bytes32[]", "internalType": "bytes32[]"}]}],
             "outputs": []},
            {"type": "event", "name": "LogicRefDenied", "anonymous": false,
             "inputs": [{"name": "logicRef", "type": "bytes32", "indexed": true, "internalType": "bytes32"}]},
            {"type": "error", "name": "DeniedLogicRef",
             "inputs": [{"name": "logicRef", "type": "bytes32", "internalType": "bytes32"}]},
            {"type": "constructor", "inputs": []}
        ]);
        let idl = json!({
            "instructions": [
                {"name": "deny_logic_ref", "accounts": [{"name": "authority"}],
                 "args": [{"name": "logic_ref", "type": {"array": ["u8", 32]}}]},
                {"name": "paused", "accounts": [], "args": [], "returns": "bool"},
                {"name": "submit", "accounts": [],
                 "args": [{"name": "action", "type": {"defined": {"name": "Action"}}}]}
            ],
            "events": [{"name": "LogicRefDeniedEvent", "discriminator": [1]}],
            "errors": [{"code": 6000, "name": "DeniedLogicRef", "msg": "denied"}],
            "types": [
                {"name": "LogicRefDeniedEvent", "type": {"kind": "struct",
                 "fields": [{"name": "logic_ref", "type": {"array": ["u8", 32]}}]}},
                {"name": "Action", "type": {"kind": "struct", "fields": [
                    {"name": "owner", "type": "pubkey"},
                    {"name": "tags", "type": {"vec": {"array": ["u8", 32]}}}]}}
            ]
        });
        let lines = compare(
            "E ↔ S",
            &abi_surface(&abi).unwrap(),
            &idl_surface(&idl).unwrap(),
        );
        let unmatched: Vec<_> = lines
            .iter()
            .filter(|l| l.outcome() != Outcome::Match)
            .collect();
        assert!(unmatched.is_empty(), "unmatched: {unmatched:#?}");
        assert_eq!(lines.len(), 6, "{lines:#?}");
    }

    /// What differs shows: an argument's type, and an entry one side lacks.
    #[test]
    fn a_differing_type_and_a_missing_entry_show() {
        let abi = json!([
            {"type": "function", "name": "setCount", "stateMutability": "nonpayable",
             "inputs": [{"name": "count", "type": "uint256", "internalType": "uint256"}],
             "outputs": []},
            {"type": "function", "name": "latestRoot", "stateMutability": "view",
             "inputs": [], "outputs": [{"name": "", "type": "bytes32", "internalType": "bytes32"}]}
        ]);
        let idl = json!({
            "instructions": [
                {"name": "set_count", "accounts": [], "args": [{"name": "count", "type": "u64"}]},
                {"name": "txdata_init", "accounts": [], "args": []}
            ],
            "accounts": [{"name": "State", "discriminator": [1]}],
            "types": [{"name": "State", "type": {"kind": "struct",
                       "fields": [{"name": "root", "type": {"array": ["u8", 32]}}]}}]
        });
        let lines = compare(
            "E ↔ S",
            &abi_surface(&abi).unwrap(),
            &idl_surface(&idl).unwrap(),
        );
        let got: Vec<(&str, Outcome)> = lines
            .iter()
            .map(|l| (l.key.as_str(), l.outcome()))
            .collect();
        assert_eq!(
            got,
            vec![
                ("account State", Outcome::OnlySolana),
                ("fn latest_root", Outcome::OnlyEvm),
                ("fn set_count", Outcome::Differs),
                ("fn txdata_init", Outcome::OnlySolana),
            ],
            "{lines:#?}"
        );
        assert_eq!(lines[2].evm, vec!["(count: u256)"]);
        assert_eq!(lines[2].solana, vec!["(count: u64)"]);
    }

    #[test]
    fn a_forge_bind_module_yields_the_abi_it_embeds() {
        let dir = std::env::temp_dir().join(format!("interface-parity-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let module = dir.join("pa.rs");
        std::fs::write(
            &module,
            "/**\n```solidity\ninterface X {}\n```\n\n...which was generated by the following JSON \
             ABI:\n```json\n[{\"type\": \"error\", \"name\": \"Nope\", \"inputs\": []}]\n```*/\n",
        )
        .unwrap();
        let s = abi_file(&module).unwrap();
        std::fs::remove_dir_all(&dir).unwrap();
        let lines = compare("E", &s, &Surface::default());
        assert_eq!(lines.len(), 1, "{lines:#?}");
        assert_eq!(lines[0].key, "error Nope");
    }
}
