name: Rust

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Tests
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Show Rust version
        run: rustc --version

      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            target
          key: rust-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: rust-

      - name: Run rustfmt
        run: just fmt-check

      - name: Build
        run: just build

      - name: Lint
        run: just lint

      - name: Run Tests
        run: just test
